---
- name: prepare dumb bare clone of future state
  git:
    repo: "{{ zuul.executor.work_root }}/{{ zuul.project.src_dir }}"
    dest: "{{ zuul.executor.work_root }}/{{ zuul.project.src_dir }}.git"
    bare: yes
  tags:
    # We don't specify git version to re-use executor state
    - skip_ansible_lint

- name: update server info for dumb http transport
  command: git update-server-info
  args:
    chdir: "{{ zuul.executor.work_root }}/{{ zuul.project.src_dir }}.git"
  tags:
    # Git module doesn't support update-server-info command
    - skip_ansible_lint

- name: create project dir on http server
  command: "oc exec {{ zm_name }} -- mkdir -p {{ zuul.project.src_dir }}.git"

- name: copy project to http server
  command: "oc rsync {{ zuul.executor.work_root }}/{{ zuul.project.src_dir }}.git/ {{ zm_name }}:/opt/app-root/src/{{ zuul.project.src_dir }}.git/"

- name: create project ImageStream spec
  openshift_raw:
    state: present
    namespace: "{{ zuul_resources['project'].namespace }}"
    definition:
      apiVersion: v1
      kind: ImageStream
      metadata:
        generation: 1
        labels:
          app: "{{ zuul.project.short_name }}"
        name: "{{ zuul.project.short_name }}"
      spec:
        lookupPolicy:
          local: false
  tags:
    # openshift_raw isn't detected as a valid module
    - skip_ansible_lint

- name: create project BuildConfig spec
  openshift_raw:
    state: present
    namespace: "{{ zuul_resources['project'].namespace }}"
    definition:
      apiVersion: v1
      kind: BuildConfig
      metadata:
        labels:
          app: "{{ zuul.project.short_name }}"
        name: "{{ zuul.project.short_name }}"
      spec:
        output:
          to:
            kind: ImageStreamTag
            name: '{{ zuul.project.short_name }}:latest'
        postCommit: {}
        resources: {}
        runPolicy: Serial
        source:
          git:
            ref: master
            uri: 'http://staging-http-server:8080/{{ zuul.project.src_dir }}.git'
          type: Git
        strategy:
          sourceStrategy:
            from:
              kind: ImageStreamTag
              name: '{{ base_image }}'
              namespace: openshift
          type: Source
        triggers:
          - type: ImageChange
          - type: ConfigChange
      status:
        lastVersion: 1
  tags:
    # openshift_raw isn't detected as a valid module
    - skip_ansible_lint

- name: wait for project image built
  command: oc get builds -o "jsonpath={.items[?(@.metadata.labels.buildconfig!='staging-http-server')].status.phase}"
  register: _project_build
  retries: 600
  delay: 1
  until: "'Complete' in _project_build.stdout"
