- hosts: all
  roles:
    - fetch-output
    - merge-output-to-logs

- hosts: all
  # NOTE(pabelanger): We ignore_errors for the following tasks as not to fail
  # successful jobs.
  ignore_errors: yes
  roles:
    - remove-build-sshkey
